### ISSUE TITLE
Cannot find library using Nuget

### ISSUE THREAD

**Issue by GianniBortoloBossini** [codemonkeychris/angular-winjs#15]
PM> Install-Package WinJS.Angular
Install-Package : Impossibile trovare il pacchetto 'WinJS.Angular'.
In riga:1 car:1
+ Install-Package WinJS.Angular
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by xirzec** [comment]
This is in NuGet now: https://www.nuget.org/packages/Angular.WinJS
