### ISSUE TITLE
Setting an `onclick` handler on a `win-app-bar-command` crashes the app

### ISSUE THREAD

**Issue by bmceldowney** [codemonkeychris/angular-winjs#40]
Using VS 2013, Windows 8.1 App Store App 

Repro steps:
1. Modify the Readme sample by adding an `onclick` attribute to one of the `win-app-bar-command` buttons, for example:
    ```<win-app-bar-command icon="'home'" label="'Home'" onclick="doSomething"></win-app-bar-command>```
2. Add the `doSomething` function to the scope
3. Run the app and click the button

Result:
The `doSomething` method does get called if you set a break point there. Regardless of whether you break or not, the app crashes with no opportunity to catch the exception when debugging in `Script Only` mode in VS 2013. Debugging in `Managed Only` mode pops up the Just-In-Time debugger with the message:

"An unhandled exception (''doSomething' is undefined') occurred in WWAHost.exe"

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

Please see if your issue still reproduces and re-open if necessary.
