### ISSUE TITLE
Navbar: hidden items still considered by WinJS

### ISSUE THREAD

**Issue by borgdylan** [codemonkeychris/angular-winjs#43]
I have a navbar with items some of which use ng-show/ng-hide to show only the navbar commands available when being logged in or logged out. The WinJS directives are still allocating space for the hidden elements (making an extra empty page in the navbar on mobile). When I tried to use ng-if to completely include/exclude teh navbar commands from the DOM , the commands reneder out of the paging control in the navbar.

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

Please see if your issue still reproduces and re-open if necessary.
