### ISSUE TITLE
win-hub-section does not get the class attribute, thus no CSS per section

### ISSUE THREAD

**Issue by Gititg** [codemonkeychris/angular-winjs#48]
Hi,

I am having some issue with the Hub & Hub-Section controls.
The hub & its sections are created, but a class I defined for CSS purposes is not written on the right instance of hub-section. The result is that I cannot set CSS style for a specific section by class name, only for all sections in the same way.
In my test I had two hub-sections, with class names "section1" and "section2". The actual sub-section does not get the class name, instead, it is only written with the hub-section mentioned under the "placeholder-holder" in the HTML - which has no effect.

(BTW, I tried to paste the html and a matching DOM explorer sample here, but the view seems to hide the html. Let me know if there is a way to add files.) 

Did anyone else try to use hub-sections with CSS classes?
Any ideas how this issue can be solved? 

thanks,
Gitit.

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

Please see if your issue still reproduces and re-open if necessary.

**Comment by rigdern** [comment]
We've moved this bug to the other repo: winjs/angular-winjs#3
