### ISSUE TITLE
Supporting WinJS 3.0

### ISSUE THREAD

**Issue by divyakumarjain** [codemonkeychris/angular-winjs#50]
I am just starting with with WinJS and was wondering if this supports WinJS3.0.

**Comment by mtycholaz** [comment]
This would be soo awesome to have.

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

The new version works with WinJS 4.0 (which should be released as a preview soon)

**Comment by mtycholaz** [comment]
Well, seems like Christmas came early this year. I'm going check this out right away! Thanks a lot!
