### ISSUE TITLE
NavBar: How does someone bind to its properties

### ISSUE THREAD

**Issue by alaingmail** [codemonkeychris/angular-winjs#51]
Hi,

I'm not having any success setting or binding to the data-win-options NavBar properties. Does anyone have any example code e.g. how to set the placement to bottom etc.

Also, I need to set the NavBar to show programmatically. I know the Windows control has this ability with a show() method, but I'm unsure how to do this via the shim.

Any help would be greatly appreciated.

Alain

**Comment by mtycholaz** [comment]
Regarding the show/hide issue, couldn't you use the build-in ng-show attribute?

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

Please see if your issue still reproduces and re-open if necessary.
