### ISSUE TITLE
Whitelist 'http'

### ISSUE THREAD

**Issue by sorskoot** [codemonkeychris/angular-winjs#52]
Hi. 
I was wondering if there is any reason why "http" isn't whitelisted?
I'm having some issues with Angular adding "unsafe:" to my image urls when using then in the template of a ListView. 

solution:
var whitelist = /^\s\*(https**?**|ms-appx|ms-appx-web|ms-appdata):/i;
$compileProvider.imgSrcSanitizationWhitelist(whitelist);
$compileProvider.aHrefSanitizationWhitelist(whitelist);

**Comment by xirzec** [comment]
We've moved the repo here:

https://github.com/winjs/angular-winjs

Please re-open your issue there. Off-hand this sounds like a security policy decision. For Windows Apps in the past there was a strong desire to always use HTTPS when making remote calls to prevent man-in-the-middle attacks and snooping for authentication tokens.
